/* Nat Watkins 03/03/2021. 
 * This project seeks to generate random graphs, calculate, and plot important transport characteristics of them. The random graphs will
 * have a percolation parameter, and there will be both undirected random graphs (Erdos-Renyi graphs) and random directed graphs. The random directed
 * graphs will be generated by taking the triangular part of an ER graph's adjacency matrix. I will calculate the ever-passage probability matrix and the first-hitting
 * time matrix from the transition matrix. 
 */

#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<math.h>
#include<time.h>

#include<gsl/gsl_math.h>
#include<gsl/gsl_block.h>
#include<gsl/gsl_vector.h>
#include<gsl/gsl_matrix.h>
#include<gsl/gsl_linalg.h>
#include<gsl/gsl_eigen.h>
#include<gsl/gsl_complex.h>
#include<gsl/gsl_complex_math.h>

#include"array_utils.h"
#include"kemeny_utils.h"
#include"graph_alloc_utils.h"
#include"graph_utils.h"

int main()
{
	void* cmd_args;
	srand(time(NULL));											// sets seed using time
	const int VERBOSE = 0;
	/* disable buffering for testing */
	setbuf(stdout, NULL);
	
	const int DIM = 50;
	const int N = DIM*DIM;
	const int MAXTIME = 1800;									// in seconds, I should add a function that keeps track of how long the program took
	const double PERCOLATION = (double)(1.0/DIM);
	
	/* allocate memory for gsl data types */
	printf("creating gsl structs...");
	gsl_eigen_nonsymmv_workspace* workspace = gsl_eigen_nonsymmv_alloc(DIM);
	gsl_permutation* permutations = gsl_permutation_alloc(DIM);
	printf("finished.\n");
	
	/* initialize the random-directed graph, and print its value */
	printf("allocating Erdos-Renyi random graph...");
	gsl_matrix* a_matER = erdos_renyi_alloc(DIM, PERCOLATION);
	printf("finished.\n");
	print_matrix(a_matER);
	gsl_matrix_write(a_matER, "adjacency_matrix.csv");
	
	/* initialize the random-directed acylic graph, and print its value */
	printf("allocating random directed acylic graph...");
	gsl_matrix* a_matDAG = random_DAG_alloc(DIM, PERCOLATION);
	printf("finished.\n");
	print_matrix(a_matDAG);
	
	/* compute the matrix laplacian and the ever-passage probability, and print its value */
	printf("computing the matrix laplacian...");
	gsl_matrix* m_mat = compute_matrix_laplacian(a_matER);
	printf("finished.\n");
	print_matrix(m_mat);
	printf("computing the ever-passage probability...");
	gsl_matrix* pinf_mat = compute_ever_passage(m_mat, permutations);
	printf("finished.\n");
	print_matrix(pinf_mat);


	/* free gsl memory */
	printf("freeing gsl memory...\n");
	gsl_eigen_nonsymmv_free(workspace);
	gsl_permutation_free(permutations);

	gsl_matrix_free(a_matER);
	gsl_matrix_free(a_matDAG);
	gsl_matrix_free(m_mat);
	gsl_matrix_free(pinf_mat);
	printf("end of program.\n");
	return 0;
}


	
	

